---
title: "2.3 Lab-Intro to R"
author: "Feliciti Milne"
date: "July 7, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 2.3.1 Basic Commands
```{r}
#Create a list
x <- c(1,3,2,5)
print(x)
#Lists can be easily written over
x = c(1,6,2)
print(x)
#Another list
y = c(1,4,3)
print(y)
#Query list property such as length
length(x)
length(y)
#Add the lists
x+y
#Now clear the lists from the variables 
ls()
rm(x,y)
ls()

#Intro to matrices
x=matrix(data=c(1,2,3,4), nrow=2, ncol=2)
print(x)
#or
matrix(c(4,3,2,1),2,2,byrow=TRUE) #not assigned to a variable 
#Perform operations on matrices
sqrt(x)
x^2


x=rnorm(50) #Generate a random samples of (n=50) with a normal distribution
y=x+rnorm(50, mean=50, sd=.1) #Generates another random sample of 50 with a mean of 50 and a standard deviation of .1)
cor(x,y) #Compute the correlation between the two randomly generated samples

#Generate another random sample of 50
set.seed(1303) #seeds allow results to be reporducable
rnorm(50)

#Generates a new random sample that can be reproduced by another user and perform operations on the sample to find its mean, variance, and standard deviation.
set.seed(3)
y=rnorm(100)
mean(y)
var(y)
sqrt(var(y)) #Mathematical way of calculating the standard deviation
sd(y) #but there is a built in function for that
```

## 2.3.2 Graphics
```{r}
x=rnorm(100)
y=rnorm(100)
plot(x,y)
plot(x,y,xlab="this is the x-axis",ylab="this is the y-axis", main = "Plot of X vs Y")
pdf("2.3.2.Figure.pdf") #save a plot as a pdf
#jpeg("2.3.2.Figure.jpeg") #or as a jpeg
plot(x,y, col="green")
dev.off()
#make some sequences 
x=seq(1,10)
x
x=1:10
x
x=seq(-pi,pi, length=50) 

y=x
f=outer(x,y,function(x,y)cos(y)/(1+x^2))
contour(x,y,f)
y=x
f=outer(x,y,function(x,y)cos(y)/(1+x^2))
contour(x,y,f,nlevels = 45,add=T)
fa=(f-t(f))/2
contour(x,y,fa,nlevels = 15)

image(x,y,fa)
persp(x,y,fa)
persp(x,y,fa, theta = 30)
persp(x,y,fa, theta = 30,phi=20)
persp(x,y,fa, theta = 30,phi=40)
persp(x,y,fa, theta = 30,phi=70)
```

## 2.3.3 Indexing Data
```{r}
A=matrix(1:16,4,4)
A
A[2,3] #index an element of a matrix
#all sorts of ways to make matrices 
A[c(1,3),c(2,4)]
A[1:3,2:4]
A[1:2,]
A[,1:2]
A[1,] #treats a called row or column as a vector
A[-c(1,3),] #negative sign called all rows/columns except those specified 
A[-c(1,3),-c(1,3,4)]
dim(A) #dimensions of a matrix
```

## 2.3.4 Loading Data
```{r}
Auto=read.table("Auto.data")
fix(Auto)
Auto=read.table("Auto.data", header=T,na.strings="?")
fix(Auto)
Auto=read.csv("Auto.csv", header=T,na.strings="?")
fix(Auto)
dim(Auto)
Auto[1:4,]
Auto=na.omit(Auto)
dim(Auto)
names(Auto)
```

## 2.3.5 Additional Graphical and Numerical Summaries
```{r}
plot(Auto$cylinders,Auto$mpg) #must call data set then  use $ to denote variable (column)
attach(Auto) #alternatively can use attach to let R know where plotting data is coming from
plot(cylinders, mpg)
cylinders=as.factor(cylinders)
plot(cylinders,mpg)
plot(cylinders,mpg, col="red")
plot(cylinders,mpg, col="red",varwidth=T)
plot(cylinders,mpg, col="red",varwidth=T, horizontal=T)
plot(cylinders,mpg, col="red",varwidth=T, xlab="cylinders", ylab="MPG")
hist(mpg)
hist(mpg,col=2)
hist(mpg,col=2,breaks = 15)
pairs(Auto)
pairs(~mpg+displacement+horsepower+weight+acceleration, Auto)
plot(horsepower,mpg)
identify(horsepower,mpg,name)
summary(Auto)
summary(mpg)
```


